#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Wed Apr 18 22:25:09 2007 from C:\Documents and Settings\Administrator\Desktop\prioritize.wxg

import wx
from Constants import *

class GuiPrioritize(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GuiPrioritize.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel = wx.Panel(self, -1)
        self.sizer_5_staticbox = wx.StaticBox(self.panel, -1, "Prioritized Sounds")
        self.sizer_4_staticbox = wx.StaticBox(self.panel, -1, "Sound Library")
        self.lblTitle = wx.StaticText(self.panel, -1, "Prioritize Sounds", style=wx.ALIGN_CENTRE)
        self.tree_ctrl_1 = wx.TreeCtrl(self.panel, -1, style=wx.TR_HAS_BUTTONS|wx.TR_LINES_AT_ROOT|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.tree_ctrl_2 = wx.TreeCtrl(self.panel, -1, style=wx.TR_HAS_BUTTONS|wx.TR_LINES_AT_ROOT|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.btnAccept = wx.Button(self.panel, -1, "Accept")
        self.btnCancel = wx.Button(self.panel, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GuiPrioritize.__set_properties
        self.SetTitle("Prioritize Sounds")
        
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GuiPrioritize.__do_layout
        szrPanel = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        sizer_1.Add(self.lblTitle, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add((10, 10), 0, 0, 0)
        sizer_4.Add(self.tree_ctrl_1, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add((10, 10), 0, 0, 0)
        sizer_5.Add(self.tree_ctrl_2, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_3.Add((10, 10), 0, 0, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_6.Add((10, 10), 0, 0, 0)
        sizer_7.Add((10, 10), 0, 0, 0)
        sizer_7.Add(self.btnAccept, 1, wx.EXPAND, 0)
        sizer_7.Add((10, 10), 0, 0, 0)
        sizer_7.Add(self.btnCancel, 1, wx.EXPAND, 0)
        sizer_7.Add((10, 10), 0, 0, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_6.Add((10, 10), 0, 0, 0)
        sizer_1.Add(sizer_6, 0, wx.EXPAND, 0)
        self.panel.SetSizer(sizer_1)
        szrPanel.Add(self.panel, 1, wx.EXPAND, 0)
        self.SetSizer(szrPanel)
        szrPanel.Fit(self)
        self.Layout()
        # end wxGlade

# end of class GuiPrioritize


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    GuiPrioritize = GuiPrioritize(None, -1, "")
    app.SetTopWindow(GuiPrioritize)
    GuiPrioritize.Show()
    app.MainLoop()
