''' Imports '''
import wx
import sys
from Constants import *

'''
' Class Name:  GuiStart
' Description: A subclass of the wx Frame class. It is diplayed when the program
'              is loaded as a welcome frame and a gateway to the rest of Sami Says.
'''
class GuiStart(wx.Frame):
    
    '''
    ' Constructor for initializing frame elements and binding window events
    '''
    def __init__(self, *args, **kwds):
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel = wx.Panel(self)
        
        self.img = wx.Image("art/banner_1100x400.png", wx.BITMAP_TYPE_PNG)
        self.picBanner = wx.StaticBitmap(self.panel, -1, wx.NullBitmap)
        self.btnStories = wx.Button(self.panel, -1, "The Bookshelf")
        self.btnStories.SetFont(wx.Font(32,wx.DECORATIVE, wx.NORMAL, wx.NORMAL, 0, "Comic Sans MS"))
        self.btnTemplates = wx.Button(self.panel, -1, "Teacher Templates")
        self.btnTemplates.SetFont(wx.Font(32,wx.DECORATIVE, wx.NORMAL, wx.NORMAL, 0, "Comic Sans MS"))
        self.__set_properties()
        self.__do_layout()

        objects = [self.panel, self.picBanner, self.btnStories, self.btnTemplates]
        for obj in objects:
            obj.Bind(wx.EVT_KEY_UP, self.onKeyUp)
            obj.Bind(wx.EVT_KEY_DOWN, self.onKeyDown)

        self.Bind(wx.EVT_BUTTON, self.btnStoriesPressed, self.btnStories)
        self.Bind(wx.EVT_BUTTON, self.btnTemplatesPressed, self.btnTemplates)
        self.Bind(wx.EVT_SIZING, self.onSize)
        self.Bind(wx.EVT_CLOSE, self.onClose)
        self.firstDown = -1
        self.env = {}
        

    '''
    ' __set_properties - Helper function for the constructor (generated by wxGlade)
    '''
    def __set_properties(self):
        self.SetTitle("Sami Says")
        self.SetPosition((0,0))
        self.SetSize(wx.DisplaySize())
        self.btnStories.SetMinSize((175, 35))
        self.btnStories.SetToolTipString("Make a story by recording and inserting sounds.")
        self.btnStories.SetDefault()
        self.btnStories.SetFocus()
        self.btnTemplates.SetMinSize((175, 35))
        self.btnTemplates.SetToolTipString("Make story templates for students to fill in.")
    # end guiStart.__set_properties

    '''
    ' __do_layout - Helper function for the constructor (generated by wxGlade)
    '''
    def __do_layout(self):
        # begin wxGlade: guiStart.__do_layout
        szrPrnt = wx.GridSizer(3, 1, 0, 0)
        szrChildSounds = wx.GridSizer(3, 3, 0, 0)
        szrChildStories = wx.GridSizer(3, 3, 0, 0)
        szrPrnt.Add(self.picBanner, 0, wx.EXPAND, 0)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.Add(self.btnStories, 1, wx.EXPAND, 0)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrPrnt.Add(szrChildStories, 0, wx.EXPAND, 0)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.Add(self.btnTemplates, 1, wx.EXPAND, 0)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrPrnt.Add(szrChildSounds, 0, wx.EXPAND, 0)
        self.panel.SetAutoLayout(True)
        self.panel.SetSizer(szrPrnt)
        self.panel.Layout()
        (w,h) = self.picBanner.GetSizeTuple()
        self.img.Rescale(w,h)
        self.picBanner.SetBitmap(wx.BitmapFromImage(self.img))
        
    '''
    ' btnStoriesPressed - Function for moving to the guiStudents frame. Bound to
    '                     the Bookshelf Button.
    '''
    def btnStoriesPressed(self, event): # wxGlade: guiStart.<event_handler>
        self.Hide()
        self.env['guiStudents'].Show()
        
    '''
    ' btnTemplatesPressed - Function for moving to the guiStories frame in teacher
    '                       mode. Bound to the Teacher Templates button.
    '''
    def btnTemplatesPressed(self, event): # wxGlade: guiStart.<event_handler>
        TEACHER_INDEX = -2
        self.Hide()
        self.env['guiStories'].setStudent(TEACHER_INDEX)
        self.env['guiStories'].Show()
    
    '''
    ' onClose - Function for handing the close event.
    '''
    def onClose(self, event):
        dialog = wx.MessageDialog(None,'Are you sure you want to leave?','Sami Says',wx.YES_NO | wx.ICON_EXCLAMATION)
        if dialog.ShowModal() == wx.ID_YES:
            dialog.Destroy()
            sys.exit()
        else:
            dialog.Destroy()
    
    '''
    ' onSize - Function for handling the resizing fo the banner image when frame is
    '          resized.
    '''
    def onSize(self, event):
        self.img = wx.Image("art/banner_1100x400.png", wx.BITMAP_TYPE_PNG)
        (w,h) = self.picBanner.GetSizeTuple()
        self.img.Rescale(w,h)
        self.picBanner.SetBitmap(wx.BitmapFromImage(self.img))
        self.Refresh()
    
    '''
    ' setEnv - Function fo setting the application environment in Sami Says
    '''
    def setEnv(self,env): 
        self.env = env
    
    '''
    ' onKeyDown - Functon for handling keyboard down events.
    '''
    def onKeyDown(self, event):
        if self.firstDown == -1:
            self.firstDown = event.GetKeyCode()
    
    '''
    ' onKeyUp - Function for handing keyboard up events. This binds the onClose
    '           function to the escape key.
    '''
    def onKeyUp(self, event):
        keyCode = event.GetKeyCode()
        if keyCode != self.firstDown:
            event.Skip()
        
        if keyCode == wx.WXK_ESCAPE:
            self.onClose(False)
        
        self.firstDown = -1

''' Handling an attempt at standalone running '''
if __name__ == "__main__":
    print 'The class "GuiStart" is not runnable.'
        
