#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun Apr 08 18:25:32 2007 from C:\Documents and Settings\Ed\Desktop\Local SamiSays\Visualization\GFXVisualv0.3.wxg

from Story import *
from SoundControl import *

import wx

class GuiVisualizer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GuiVisualizer.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel = wx.Panel(self, -1)
        self.title = wx.StaticText(self.panel, -1, 'Story Creation')
        self.instructions = wx.TextCtrl(self.panel, -1, 'Record more clips with the [space bar].  Navigate through clips with the [left and right arrows].  Insert sounds with the [down arrow].', style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.statsLabel = wx.StaticText(self.panel, -1, '')
        self.infoLabel = wx.StaticText(self.panel, -1, 'Story Information')
        self.instructionLabel = wx.StaticText(self.panel, -1, 'Instructions')

        # binding of events
        self.Bind(wx.EVT_KILL_FOCUS, self.handleFocus, self)
        self.Bind(wx.EVT_SHOW, self.handleShow, self)
        
        self.visible = False

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        
    def __set_properties(self):
        # begin wxGlade: GuiVisualizer.__set_properties
        self.SetTitle("Sami Says")
        self.SetPosition((0,0))
        self.SetSize(wx.DisplaySize())
        self.title.SetFont(wx.Font(28, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.statsLabel.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.instructions.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.infoLabel.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.instructionLabel.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GuiVisualizer.__do_layout
        title_boxesSizer = wx.BoxSizer(wx.VERTICAL)
        labelsSizer = wx.BoxSizer(wx.HORIZONTAL)
        boxesSizer = wx.BoxSizer(wx.HORIZONTAL)
        informationSizer = wx.BoxSizer(wx.VERTICAL)
        title_sizer = wx.BoxSizer(wx.HORIZONTAL)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 1, 0, 0)
        title_sizer.Add(self.title, 0, 0, 0)
        title_sizer.Add((20, 20), 1, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_boxesSizer.Add(title_sizer, 1, wx.EXPAND, 0)
        boxesSizer.Add((20, 20), 0, 0, 0)
        informationSizer.Add(self.statsLabel, 0, 0, 0)
        informationSizer.Add((20, 20), 0, 0, 0)
        boxesSizer.Add(informationSizer, 1, wx.EXPAND, 0)
        boxesSizer.Add((20, 20), 0, 0, 0)
        boxesSizer.Add(self.instructions, 1, wx.EXPAND, 0)
        boxesSizer.Add((20, 20), 0, 0, 0)
        title_boxesSizer.Add(boxesSizer, 10, wx.EXPAND, 0)
        labelsSizer.Add((20, 20), 0, 0, 0)
        labelsSizer.Add(self.infoLabel, 0, 0, 0)
        labelsSizer.Add((20, 20), 1, 0, 0)
        labelsSizer.Add(self.instructionLabel, 0, 0, 0)
        labelsSizer.Add((20, 20), 0, 0, 0)
        title_boxesSizer.Add(labelsSizer, 1, wx.EXPAND, 0)
        self.panel.SetSizer(title_boxesSizer)
        self.Layout()
        self.panel.Layout()
        # end wxGlade
        
    def handleFocus(self, event):
        if self.visible:
            self.SetFocus()
    
    def handleShow(self, event):
        if not self.visible:
            self.updateStats()
        self.visible = not self.visible
        
    
    def setEnv(self,env): 
        self.env = env

    def setInstructions(self, instructs):
	    self.instructions.WriteText(instructs)

    def updateStats(self):
        stats = self.env['story'].getStats()
        min,sec = getDuration(self.env['story'].getStoryBytes())
        
        if (min > 0):
            self.statsLabel.SetLabel('Duration:  %d m %.2f s\n\nNumber of Clips:  %d\nRecorded Sounds: %d\nInserted Sounds:  %d\nManipulated Sounds:  %d\nLocked (Teacher) Sounds:  %d\nBreaks:  %d'
                               % (min, sec, len(self.env['story'])-1, stats[REC], stats[SND], stats[SFX], stats[LCK], stats[BRK]))
        else :
            self.statsLabel.SetLabel('Duration:  %.2f s\n\nNumber of Clips:  %d\nRecorded Sounds: %d\nInserted Sounds:  %d\nManipulated Sounds:  %d\nLocked (Teacher) Sounds:  %d\nBreaks:  %d'
                               % (sec, len(self.env['story'])-1, stats[REC], stats[SND], stats[SFX], stats[LCK], stats[BRK]))
        

# end of class GuiVisualizer


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_5 = GuiVisualizer(None, -1, "")
    app.SetTopWindow(frame_5)
    frame_5.Show()
    app.MainLoop()
