#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Thu Feb 08 18:05:26 2007

import wx
import sys

class GuiStart(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: guiStart.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.picBanner = wx.StaticBitmap(self, -1, wx.NullBitmap)
        self.filler00 = wx.Panel(self, -1)
        self.filler01 = wx.Panel(self, -1)
        self.filler02 = wx.Panel(self, -1)
        self.filler03 = wx.Panel(self, -1)
        self.btnStories = wx.Button(self, -1, "Stories")
        self.btnStories.SetFont(wx.Font(14,wx.SWISS, wx.NORMAL, wx.NORMAL))
        self.filler04 = wx.Panel(self, -1)
        self.filler05 = wx.Panel(self, -1)
        self.filler06 = wx.Panel(self, -1)
        self.filler07 = wx.Panel(self, -1)
        self.filler8 = wx.Panel(self, -1)
        self.btnSounds = wx.Button(self, -1, "Sounds")
        self.btnSounds.SetFont(wx.Font(14,wx.SWISS, wx.NORMAL, wx.NORMAL))
        self.filler09 = wx.Panel(self, -1)
        self.filler10 = wx.Panel(self, -1)
        self.filler11 = wx.Panel(self, -1)
        self.filler12 = wx.Panel(self, -1)
        self.filler13 = wx.Panel(self, -1)
        self.filler14 = wx.Panel(self, -1)
        self.filler15 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnStoriesPressed, self.btnStories)
        self.Bind(wx.EVT_BUTTON, self.btnSoundsPressed, self.btnSounds)
        
        # Added By Patrick
        self.Bind(wx.EVT_CLOSE, self.onClose)
        self.env = []
        
    # end guiStart.__init__

    def __set_properties(self):
        # begin wxGlade: guiStart.__set_properties
        self.SetTitle("Sami Says")
        self.SetSize((400, 500))
        self.btnStories.SetMinSize((175, 35))
        self.btnStories.SetToolTipString("Make a story by recording and inserting sounds.")
        self.btnStories.SetDefault()
        self.btnSounds.SetMinSize((175, 35))
        self.btnSounds.SetToolTipString("Manage how sounds are organized when making stories.")
    # end guiStart.__set_properties

    def __do_layout(self):
        # begin wxGlade: guiStart.__do_layout
        szrPrnt = wx.BoxSizer(wx.VERTICAL)
        szrChild = wx.GridSizer(3, 1, 0, 0)
        szrChildSounds = wx.FlexGridSizer(3, 3, 0, 0)
        szrChildStories = wx.FlexGridSizer(3, 3, 0, 0)
        szrChild.Add(self.picBanner, 0, wx.EXPAND|wx.EXPAND, 0)
        szrChildStories.Add(self.filler00, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.filler01, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.filler02, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.filler03, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.btnStories, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.EXPAND, 0)
        szrChildStories.Add(self.filler04, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.filler05, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.filler06, 1, wx.EXPAND, 0)
        szrChildStories.Add(self.filler07, 1, wx.EXPAND, 0)
        szrChildStories.AddGrowableRow(0)
        szrChildStories.AddGrowableRow(2)
        szrChildStories.AddGrowableCol(0)
        szrChildStories.AddGrowableCol(2)
        szrChild.Add(szrChildStories, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler8, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.btnSounds, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.EXPAND, 0)
        szrChildSounds.Add(self.filler09, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler10, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler11, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler12, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler13, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler14, 1, wx.EXPAND, 0)
        szrChildSounds.Add(self.filler15, 1, wx.EXPAND, 0)
        szrChildSounds.AddGrowableRow(1)
        szrChildSounds.AddGrowableRow(2)
        szrChildSounds.AddGrowableCol(0)
        szrChildSounds.AddGrowableCol(2)
        szrChild.Add(szrChildSounds, 1, wx.EXPAND, 0)
        szrPrnt.Add(szrChild, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(szrPrnt)
        self.Layout()
    # end guiStart.__do_layout

    def btnStoriesPressed(self, event): # wxGlade: guiStart.<event_handler>
        self.Hide()
        self.env[2].Show()
    # end btnStoriesPressed

    def btnSoundsPressed(self, event): # wxGlade: guiStart.<event_handler>
        print 'btnSoundsPressed not yet implemented'
    # end btnSoundPressed
    
    def onClose(self, event):
        dialog = wx.MessageDialog(None,'Are you sure you want to leave?','Sami Says',wx.YES_NO)
        if dialog.ShowModal() == wx.ID_YES:
            dialog.Destroy()
            sys.exit()
        else:
            dialog.Destroy()
    
    def setEnv(self,env): 
        self.env = env   
    # end of setEnv

# end of class guiStart


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frmMain = GuiStart(None, -1, "")
    app.SetTopWindow(frmMain)
    frmMain.Show()
    app.MainLoop()
