#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Thu Feb 08 18:05:26 2007

import wx
import sys

class GuiStart(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: guiStart.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel = wx.Panel(self)
        
        # Loading the title
        self.img = wx.Image("art/banner_1100x400.png", wx.BITMAP_TYPE_PNG)
        
        self.picBanner = wx.StaticBitmap(self.panel, -1, wx.NullBitmap)
        self.btnStories = wx.Button(self.panel, -1, "The Classroom")
        self.btnStories.SetFont(wx.Font(32,wx.DECORATIVE, wx.NORMAL, wx.NORMAL))
        self.btnSounds = wx.Button(self.panel, -1, "Sounds")
        self.btnSounds.SetFont(wx.Font(32,wx.DECORATIVE, wx.NORMAL, wx.NORMAL))
        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnStoriesPressed, self.btnStories)
        self.Bind(wx.EVT_BUTTON, self.btnSoundsPressed, self.btnSounds)
        self.Bind(wx.EVT_SIZING, self.onSize)
        self.Bind(wx.EVT_CLOSE, self.onClose)
        self.env = {}
        
    # end guiStart.__init__

    def __set_properties(self):
        # begin wxGlade: guiStart.__set_properties
        self.SetTitle("Sami Says")
        self.SetPosition((0,0))
        self.SetSize(wx.DisplaySize())
        self.btnStories.SetMinSize((175, 35))
        self.btnStories.SetToolTipString("Make a story by recording and inserting sounds.")
        self.btnStories.SetDefault()
        self.btnStories.SetFocus()
        self.btnSounds.SetMinSize((175, 35))
        self.btnSounds.SetToolTipString("Manage how sounds are organized when making stories.")
    # end guiStart.__set_properties

    def __do_layout(self):
        # begin wxGlade: guiStart.__do_layout
        szrPrnt = wx.GridSizer(3, 1, 0, 0)
        szrChildSounds = wx.GridSizer(3, 3, 0, 0)
        szrChildStories = wx.GridSizer(3, 3, 0, 0)
        szrPrnt.Add(self.picBanner, 0, wx.EXPAND, 0)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.Add(self.btnStories, 1, wx.EXPAND, 0)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrChildStories.AddSpacer(-1)
        szrPrnt.Add(szrChildStories, 0, wx.EXPAND, 0)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.Add(self.btnSounds, 1, wx.EXPAND, 0)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrChildSounds.AddSpacer(-1)
        szrPrnt.Add(szrChildSounds, 0, wx.EXPAND, 0)
        self.panel.SetAutoLayout(True)
        self.panel.SetSizer(szrPrnt)
        self.panel.Layout()
        (w,h) = self.picBanner.GetSizeTuple()
        self.img.Rescale(w,h)
        self.picBanner.SetBitmap(wx.BitmapFromImage(self.img))
    # end guiStart.__do_layout

    def btnStoriesPressed(self, event): # wxGlade: guiStart.<event_handler>
        self.Hide()
        self.env['guiStudents'].Show()
    # end btnStoriesPressed

    def btnSoundsPressed(self, event): # wxGlade: guiStart.<event_handler>
        print 'btnSoundsPressed not yet implemented'
    # end btnSoundPressed
    
    def onClose(self, event):
        dialog = wx.MessageDialog(None,'Are you sure you want to leave?','Sami Says',wx.YES_NO | wx.ICON_EXCLAMATION)
        if dialog.ShowModal() == wx.ID_YES:
            dialog.Destroy()
            sys.exit()
        else:
            dialog.Destroy()
            
    def onSize(self, event):
        self.img = wx.Image("SamiSays.jpg", wx.BITMAP_TYPE_JPEG)
        (w,h) = self.picBanner.GetSizeTuple()
        self.img.Rescale(w,h)
        self.picBanner.SetBitmap(wx.BitmapFromImage(self.img))
        self.Refresh()
    
    def setEnv(self,env): 
        self.env = env   
    # end of setEnv

# end of class guiStart


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frmMain = GuiStart(None, -1, "")
    app.SetTopWindow(frmMain)
    frmMain.Show()
    app.MainLoop()
