#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun Apr 08 18:25:32 2007 from C:\Documents and Settings\Ed\Desktop\Local SamiSays\Visualization\GFXVisualv0.3.wxg

import wx

class GuiVisualizer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GuiVisualizer.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.title = wx.StaticText(self.panel_1, -1, "Story Creation")
        self.tot_len = wx.StaticText(self.panel_1, -1, "Total Length:")
        self.num_effects = wx.StaticText(self.panel_1, -1, "Number of Effects:")
        self.num_recorded = wx.StaticText(self.panel_1, -1, "Recorded Clips:")
        self.instructions = wx.TextCtrl(self.panel_1, -1, "Record more clips with the [space bar].  Navigate through clips with the [left and right arrows].  Insert sounds with the [down arrow].", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.info_label = wx.StaticText(self.panel_1, -1, "Story Information")
        self.instruction_label = wx.StaticText(self.panel_1, -1, "Instructions")

        # binding of events
        self.Bind(wx.EVT_KILL_FOCUS, self.handleFocus, self)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GuiVisualizer.__set_properties
        self.SetTitle("Sami Says")
        self.SetPosition((0,0))
        self.SetSize(wx.DisplaySize())
        self.title.SetFont(wx.Font(28, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.tot_len.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.num_effects.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.num_recorded.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.instructions.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.info_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.instruction_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GuiVisualizer.__do_layout
        title_boxes_sizer = wx.BoxSizer(wx.VERTICAL)
        labels_sizer = wx.BoxSizer(wx.HORIZONTAL)
        boxes_sizer = wx.BoxSizer(wx.HORIZONTAL)
        information_sizer = wx.BoxSizer(wx.VERTICAL)
        title_sizer = wx.BoxSizer(wx.HORIZONTAL)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 1, 0, 0)
        title_sizer.Add(self.title, 0, 0, 0)
        title_sizer.Add((20, 20), 1, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_boxes_sizer.Add(title_sizer, 1, wx.EXPAND, 0)
        boxes_sizer.Add((20, 20), 0, 0, 0)
        information_sizer.Add(self.tot_len, 0, 0, 0)
        information_sizer.Add(self.num_effects, 0, 0, 0)
        information_sizer.Add(self.num_recorded, 0, 0, 0)
        information_sizer.Add((20, 20), 0, 0, 0)
        boxes_sizer.Add(information_sizer, 1, wx.EXPAND, 0)
        boxes_sizer.Add((20, 20), 0, 0, 0)
        boxes_sizer.Add(self.instructions, 1, wx.EXPAND, 0)
        boxes_sizer.Add((20, 20), 0, 0, 0)
        title_boxes_sizer.Add(boxes_sizer, 10, wx.EXPAND, 0)
        labels_sizer.Add((20, 20), 0, 0, 0)
        labels_sizer.Add(self.info_label, 0, 0, 0)
        labels_sizer.Add((20, 20), 1, 0, 0)
        labels_sizer.Add(self.instruction_label, 0, 0, 0)
        labels_sizer.Add((20, 20), 0, 0, 0)
        title_boxes_sizer.Add(labels_sizer, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(title_boxes_sizer)
        self.Layout()
        self.panel_1.Layout()
        # end wxGlade
        
    def handleFocus(self, event):
        self.SetFocus()

    def setInstructions(self, instructs):
	    self.instructions.WriteText(instructs)

    def setLen(self, len):
        self.tot_len = wx.StaticText(self.panel_1, -1, "Total Length: " + len)

    def setFX(self, num_fx):
        self.num_effects = wx.StaticText(self.panel_1, -1, "Number of Effects: " + num_fx)

    def setClips(self, num_clips):
        self.num_recorded = wx.StaticText(self.panel_1, -1, "Recorded Clips: " + num_clips)


# end of class GuiVisualizer


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_5 = GuiVisualizer(None, -1, "")
    app.SetTopWindow(frame_5)
    frame_5.Show()
    app.MainLoop()
