#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun Apr 08 18:25:32 2007 from C:\Documents and Settings\Ed\Desktop\Local SamiSays\Visualization\GFXVisualv0.3.wxg

from Story import *

import wx

class GuiVisualizer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GuiVisualizer.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.title = wx.StaticText(self.panel_1, -1, 'Story Creation')
        self.instructions = wx.TextCtrl(self.panel_1, -1, 'Record more clips with the [space bar].  Navigate through clips with the [left and right arrows].  Insert sounds with the [down arrow].', style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.stats_label = wx.StaticText(self.panel_1, -1, '')
        self.info_label = wx.StaticText(self.panel_1, -1, 'Story Information')
        self.instruction_label = wx.StaticText(self.panel_1, -1, 'Instructions')

        # binding of events
        self.Bind(wx.EVT_KILL_FOCUS, self.handleFocus, self)
        self.Bind(wx.EVT_SHOW, self.handleShow, self)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        
    def __set_properties(self):
        # begin wxGlade: GuiVisualizer.__set_properties
        self.SetTitle("Sami Says")
        self.SetPosition((0,0))
        self.SetSize(wx.DisplaySize())
        self.title.SetFont(wx.Font(28, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.stats_label.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.instructions.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.info_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.instruction_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GuiVisualizer.__do_layout
        title_boxes_sizer = wx.BoxSizer(wx.VERTICAL)
        labels_sizer = wx.BoxSizer(wx.HORIZONTAL)
        boxes_sizer = wx.BoxSizer(wx.HORIZONTAL)
        information_sizer = wx.BoxSizer(wx.VERTICAL)
        title_sizer = wx.BoxSizer(wx.HORIZONTAL)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 1, 0, 0)
        title_sizer.Add(self.title, 0, 0, 0)
        title_sizer.Add((20, 20), 1, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_sizer.Add((20, 20), 0, 0, 0)
        title_boxes_sizer.Add(title_sizer, 1, wx.EXPAND, 0)
        boxes_sizer.Add((20, 20), 0, 0, 0)
        information_sizer.Add(self.stats_label, 0, 0, 0)
        information_sizer.Add((20, 20), 0, 0, 0)
        boxes_sizer.Add(information_sizer, 1, wx.EXPAND, 0)
        boxes_sizer.Add((20, 20), 0, 0, 0)
        boxes_sizer.Add(self.instructions, 1, wx.EXPAND, 0)
        boxes_sizer.Add((20, 20), 0, 0, 0)
        title_boxes_sizer.Add(boxes_sizer, 10, wx.EXPAND, 0)
        labels_sizer.Add((20, 20), 0, 0, 0)
        labels_sizer.Add(self.info_label, 0, 0, 0)
        labels_sizer.Add((20, 20), 1, 0, 0)
        labels_sizer.Add(self.instruction_label, 0, 0, 0)
        labels_sizer.Add((20, 20), 0, 0, 0)
        title_boxes_sizer.Add(labels_sizer, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(title_boxes_sizer)
        self.Layout()
        self.panel_1.Layout()
        # end wxGlade
        
    def handleFocus(self, event):
        self.SetFocus()
    
    def handleShow(self, event):
        self.updateStats()
    
    def setEnv(self,env): 
        self.env = env

    def setInstructions(self, instructs):
	    self.instructions.WriteText(instructs)

    def updateStats(self):
        stats = self.env['story'].getStats()
        self.stats_label.SetLabel('Total Length:  %d\nRecorded Sounds: %d\nInserted Sounds:  %d\nManipulated Sounds:  %d\nLocked (Teacher) Sounds:  %d\nBreaks:  %d'
                               % (len(self.env['story'])-1, stats[REC], stats[SND], stats[SFX], stats[LCK], stats[BRK]))
        

# end of class GuiVisualizer


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_5 = GuiVisualizer(None, -1, "")
    app.SetTopWindow(frame_5)
    frame_5.Show()
    app.MainLoop()
